allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@effect/platform-node-shared@4.0.0-rc.117'
  - '@effect/platform-node@4.0.0-rc.117'
  - '@effect/sql-sqlite-node@4.0.0-rc.117'
  - effect@4.0.0-rc.117
